### ISSUE TITLE
error parsing config: repo config not allowed to set 'workflow' key: server-side config needs 'allowed_overrides: [workflow]'

### ISSUE THREAD

**Issue by jamengual** [cresta/atlantis-drift-detection#24]
I was reading the code here:

https://github.com/cresta/atlantis-drift-detection/blob/52efcd54d3b58dd9b0e9ef9232edd7b83fa287e6/internal/atlantis/config.go#L34

it looks like the action is parsing the repo side config `atlantis.yaml` and trying to find something that is `not` defined in there but instead in the `repos.yaml` config on the server side.

https://www.runatlantis.io/docs/custom-workflows.html#usage

`allowed_overrides: [workflow]` is a config on the server side that will not be on the monorepo where the terraform code resides.

the error I'm getting :

```
{"level":"info","ts":1672897241.4019797,"caller":"atlantis-drift-detection/main.go:108","msg":"setting up workflow notification"}
{"level":"debug","ts":1672897241.4021816,"caller":"atlantis-drift-detection/main.go:67","msg":"call call git clone ***github.com/jamengual/atlantmos.git /tmp/gogit2211482022"}
{"level":"debug","ts":1672897241.7879[17](https://github.com/jamengual/atlantmos/actions/runs/3844182193/jobs/6547064960#step:3:18)9,"caller":"atlantis-drift-detection/main.go:67","msg":"done call git clone ***github.com/jamengual/atlantmos.git /tmp/gogit2211482022","stdout":"","stderr":"Cloning into '/tmp/gogit2211482022'...\n"}
{"level":"panic","ts":1672897241.791465,"caller":"atlantis-drift-detection/main.go:143","msg":"failed to drift","error":"failed to parse repo config: error parsing config: repo config not allowed to set 'workflow' key: server-side config needs 'allowed_overrides: [workflow]'","stacktrace":"main.main\n\t/app/cmd/atlantis-drift-detection/main.go:143\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
panic: failed to drift

goroutine 1 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x1?, 0xc00012eea0?, {0x0?, 0x0?, 0xc000120260?})
	/go/pkg/mod/go.uber.org/zap@v1.22.0/zapcore/entry.go:198 +0x65
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00012eb60, {0xc00009d280, 0x1, 0x1})
	/go/pkg/mod/go.uber.org/zap@v1.22.0/zapcore/entry.go:264 +0x3ec
go.uber.org/zap.(*Logger).Panic(0xc000[18](https://github.com/jamengual/atlantmos/actions/runs/3844182193/jobs/6547064960#step:3:19)4a[20](https://github.com/jamengual/atlantmos/actions/runs/3844182193/jobs/6547064960#step:3:21)?, {0xd40a10?, 0xc000046068?}, {0xc00009d280, 0x1, 0x1})
	/go/pkg/mod/go.uber.org/zap@v1.[22](https://github.com/jamengual/atlantmos/actions/runs/3844182193/jobs/6547064960#step:3:23).0/logger.go:[25](https://github.com/jamengual/atlantmos/actions/runs/3844182193/jobs/6547064960#step:3:26)1 +0x59
main.main()
	/app/cmd/atlantis-drift-detection/main.go:143 +0x12e5
```

And at this point there is 0 request to the atlantis server yet.

**Comment by cep21** [comment]
I'm a bit confused. Can you paste a minimal valid config that fails ParseRepoConfig ?

**Comment by jamengual** [comment]
```
---
version: 3
automerge: true
delete_source_branch_on_merge: true
parallel_plan: true
parallel_apply: true
allowed_regexp_prefixes:
- lab/
- staging/
- prod/
projects:
- name: pepe-ue2-lab-cloudtrail
  workspace: pepe-ue2-lab
  workflow: workflow-1
  dir: components/terraform/cloudtrail
  terraform_version: v1.2.9
  delete_source_branch_on_merge: false
  autoplan:
    enabled: true
    when_modified:
    - '**/*.tf'
    - $PROJECT_NAME.tfvars.json
  apply_requirements:
  - approved
```

**Comment by cep21** [comment]
There's no way for the atlantis API to get access to server side config.  What do you suggest instead?

**Comment by jamengual** [comment]
I think the action needs to assume that the `atlantis.yaml` is valid, since this was activated intentionally on a repo that is already working on atlantis, what I mean is, you will never add this action without already having an atlantis workflow working.

so the action can still try to validate the `atlantis.yaml` but is should not try to check if the server side is correct and should assume it is.

**Comment by jamengual** [comment]
remember that the `atlantis.yaml` file will never contain any of the `repo.yaml` configs in it, like : 
```
repos:
- id: /.*/
  allowed_overrides: [apply_requirements, workflow, delete_source_branch_on_merge]
  allow_custom_workflows: true
  apply_requirements: [mergeable]
```

**Comment by cep21** [comment]
I believe https://github.com/cresta/atlantis-drift-detection/pull/25 may fix it?

**Comment by jamengual** [comment]
yes, that might do it, are you going to merge it soon?

**Comment by cep21** [comment]
merged v0.0.9

**Comment by jamengual** [comment]
I'm testing 0.0.9 and I'm seeing this request to my atlantis server:

```
{"Repository":"jamengual/atlantmos","Ref":"master","Type":"Github","Projects":null,"Paths":[{"Directory":"components/terraform/null-resource","Workspace":"pepe-ue2-lab"}]}
```

then on my atlantis server logs I see : 
```{"level":"error","ts":"2023-01-06T15:21:23.533-0800","caller":"events/instrumented_project_command_builder.go:66","msg":"Error building plan commands: checking if workspace exists: stat /Users/pepe.amengual/.atlantis/repos/jamengual/atlantmos/0/default: no such file or directory"```


for some reason it keeps pointing to master , even though I changed the ref and somehow is not finding my project 👍🏽 

```
version: 3
automerge: true
delete_source_branch_on_merge: true
parallel_plan: true
parallel_apply: true
allowed_regexp_prefixes:
- lab/
- staging/
- prod/
projects:
- name: pepe-ue2-lab-null-resource
  workspace: pepe-ue2-lab
  workflow: workflow-1
  dir: components/terraform/null-resource
  terraform_version: v1.2.9
  delete_source_branch_on_merge: false
  autoplan:
    enabled: true
    when_modified:
    - '**/*.tf'
    - $PROJECT_NAME.tfvars.json
  apply_requirements:
  - approved
workflows:
  workflow-1:
    apply:
      steps:
      - run: terraform apply $PLANFILE
    plan:
      steps:
      - run: terraform init -input=false --reconfigure
      - run: terraform workspace select $WORKSPACE || terraform workspace new $WORKSPACE
      - run: terraform plan -input=false -refresh -out $PLANFILE -var-file $PROJECT_NAME.tfvars.json
```

**Comment by jamengual** [comment]
my action settings: 

```
    - name: detect drift
        uses: cresta/atlantis-drift-detection@v0.0.9
        env:
          ATLANTIS_HOST: ${{ secrets.WEBHOOK_URL }}
          ATLANTIS_TOKEN: ${{ secrets.WEBHOOK_SECRET }}
          REPO: jamengual/atlantmos
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          #DYNAMODB_TABLE: atlantis-drift-detection
          #DIRECTORY_WHITELIST: /
          WORKFLOW_OWNER: jamengual
          WORKFLOW_REPO: atlantmos
          WORKFLOW_ID: trigger_undrifter.yaml
          WORKFLOW_REF: main
          GITHUB_APP_ID: $ {{ secrets.OUR_APP_ID_FOR_CREATING_PRS }}
          GITHUB_INSTALLATION_ID: $ {{ secrets.OUR_APP_ID_FOR_CREATING_PRS }}
          GITHUB_PEM_KEY: ${{ secrets.OUR_PEM_ID_FOR_CREATING_PRS }}
          CACHE_VALID_DURATION: 168h
```
