### ISSUE TITLE
AtlantisClient.PlanSummary fatal: couldn't find remote ref pull/0/head\n: exit status 128"

### ISSUE THREAD

**Issue by kosta709** [cresta/atlantis-drift-detection#305]
Hi,
I cannot get it working. When it calls Atlantis Plan it does not pass PR , so in Atlantis Log I see  
```
"events/instrumented_project_command_builder.go:75","msg":"Error building plan commands: running git fetch origin pull/0/head:: fatal: couldn't find remote ref pull/0/head\n: exit status 128","json":{},"stacktrace":"github.com/runatlantis/atlantis/server/events.
```

## the log of the action:
```
Run cresta/atlantis-drift-detection@v1.0.0
/usr/bin/docker run --name ghcriocrestaatlantisdriftdetectionv1_ab071f --label 464018 --workdir /github/workspace --rm -e "AWS_DEFAULT_REGION" -e "AWS_REGION" -e "AWS_ACCESS_KEY_ID" -e "AWS_SECRET_ACCESS_KEY" -e "AWS_SESSION_TOKEN" -e "ATLANTIS_HOST" -e "ATLANTIS_TOKEN" -e "REPO" -e "GITHUB_TOKEN" -e "SLACK_WEBHOOK_URL" -e "WORKFLOW_OWNER" -e "WORKFLOW_REPO" -e "WORKFLOW_ID" -e "WORKFLOW_REF" -e "CACHE_VALID_DURATION" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_ID_TOKEN_REQUEST_URL" -e "ACTIONS_ID_TOKEN_REQUEST_TOKEN" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/terraform-for-test/terraform-for-test":"/github/workspace" ghcr.io/cresta/atlantis-drift-detection:v1
{"level":"info","ts":1746527549.5547125,"caller":"atlantis-drift-detection/main.go:101","msg":"setting up slack webhook notification"}
{"level":"info","ts":1746527549.5552535,"caller":"atlantis-drift-detection/main.go:113","msg":"setting up workflow notification"}
{"level":"debug","ts":1746527549.555986,"caller":"atlantis-drift-detection/main.go:68","msg":"call call git clone ***github.com/-----/terraform-for-test.git /tmp/gogit1386487324"}
{"level":"debug","ts":1746527549.938081,"caller":"atlantis-drift-detection/main.go:68","msg":"done call git clone ***github.com/-----/terraform-for-test.git /tmp/gogit1386487324","stdout":"","stderr":"Cloning into '/tmp/gogit1386487324'...\n"}
{"level":"info","ts":1746527549.9384866,"caller":"drifter/drifter.go:124","msg":"Checking for drifted workspaces","drifter":"true","dir":"terraform-confs/test01"}
{"level":"warn","ts":1746527551.7894344,"caller":"drifter/drifter.go:155","msg":"Temporary error.  Will try again later.","drifter":"true","error":"error decoding plan response(code:500)(status:500 Internal Server Error)(body:): json: cannot unmarshal string into Go struct field Result.Error of type error"}
{"level":"warn","ts":1746527553.0878196,"caller":"drifter/drifter.go:155","msg":"Temporary error.  Will try again later.","drifter":"true","error":"error decoding plan response(code:500)(status:500 Internal Server Error)(body:): json: cannot unmarshal string into Go struct field Result.Error of type error"}
{"level":"warn","ts":1746527554.451908,"caller":"drifter/drifter.go:155","msg":"Temporary error.  Will try again later.","drifter":"true","error":"error decoding plan response(code:500)(status:500 Internal Server Error)(body:): json: cannot unmarshal string into Go struct field Result.Error of type error"}
{"level":"warn","ts":1746527555.8290062,"caller":"drifter/drifter.go:155","msg":"Temporary error.  Will try again later.","drifter":"true","error":"error decoding plan response(code:500)(status:500 Internal Server Error)(body:): json: cannot unmarshal string into Go struct field Result.Error of type error"}
{"level":"info","ts":1746527555.8290503,"caller":"drifter/drifter.go:215","msg":"Checking for extra workspaces","drifter":"true","dir":"terraform-confs/test01"}
{"level":"info","ts":1746527555.8290625,"caller":"terraform/terraform.go:33","msg":"Initializing terraform","terraform":"true","dir":"terraform-confs/test01"}
{"level":"info","ts":1746527562.4391363,"caller":"terraform/terraform.go:47","msg":"Listing workspaces","terraform":"true","dir":"terraform-confs/test01"}
```

## atlantis-drift-detection.yml
```
name: Drift detection
on:
  workflow_dispatch:
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  drift:
    name: detects drift
    runs-on: ubuntu-latest
    permissions:
      contents: write      # required to merge PRs
      actions: write       # required for plan persistence
      id-token: write      # required for workload-identity-federation
      pull-requests: write # required to post PR comments
      issues: read         # required to check if PR number is an issue or not
      statuses: write      # required to validate combined PR status
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::---------:role/github-deployer
          role-session-name: github-deployer
          aws-region: us-east-1
      - name: detect drift
        uses: cresta/atlantis-drift-detection@v1.0.0
        env:
          ATLANTIS_HOST: https://atlantis-tf.-----.com
          ATLANTIS_TOKEN: ${{ secrets.ATLANTIS_TOKEN }}
          REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.ATLANTIS_SLACK_WEBHOOK_URL }}
          # DYNAMODB_TABLE: atlantis-drift-detection
          WORKFLOW_OWNER: -----
          WORKFLOW_REPO: terraform-for-test
          WORKFLOW_ID: submit-pr-for-drift-detect.yml
          WORKFLOW_REF: ${{ github.ref_name }}
          # GITHUB_APP_ID: 123456
          # GITHUB_INSTALLATION_ID: 123456
          # GITHUB_PEM_KEY:
          CACHE_VALID_DURATION: 168h
```

## submit-pr-for-drift-detect.yml
```
name: Force a terraform PR
on:
  workflow_dispatch:
    inputs:
      directory:
        description: >-
          Which directory to force a terraform workflow upon
        required: true
        type: string
jobs:
  plantrigger:
    runs-on: ubuntu-latest
    name: Force terraform plan PR
    permissions:
        contents: write      # required to merge PRs
        actions: write       # required for plan persistence
        id-token: write      # required for workload-identity-federation
        pull-requests: write # required to post PR comments
        issues: read         # required to check if PR number is an issue or not
        statuses: write      # required to validate combined PR status
    steps:
      # We use an application to make PRs, rather than hard code a user token
    #   - name: Generate token
    #     id: generate_token
    #     uses: peter-murray/workflow-application-token-action@v1
    #     with:
    #       application_id: {{ secrets.OUR_APP_ID_FOR_CREATING_PRS }}
    #       application_private_key: {{ secrets.OUR_PEM_ID_FOR_CREATING_PRS }}
      - name: Checkout
        uses: actions/checkout@v2
      - run: ./scripts/update-drift-detect-pr.sh ${DIR}
        env:
          DIR: ${{ github.event.inputs.directory }}
      - name: Create PR to terraform repo
        uses: peter-evans/create-pull-request@v3
        id: make-pr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: tf-drift-replan-00000-${{ github.event.inputs.directory }}
          delete-branch: true
          title: "Force replan of directory ${{ github.event.inputs.directory }}"
          labels: forced-workflow
          committer: Forced Replan <noreply@cresta.ai>
          body: "A forced replan of this directory was triggered via github actions"
          commit-message: "Regenerated plan for ${{ github.event.inputs.directory }}"
```

## Possible Cause - drift-detection calls atlantis API without PR 
probably because it calls Atlantis Plan API without PR and with hardcoded "master"
[Atlantis Plan API Call](https://github.com/cresta/atlantis-drift-detection/blob/94cf676e86bad65ab028f95e69f48679ea7dd560/internal/drifter/drifter.go#L145)
```
pr, err := d.AtlantisClient.PlanSummary(ctx, &atlantis.PlanSummaryRequest{
	Repo:      d.Repo,
	Ref:       "master",
	Type:      "Github",
	Dir:       dir,
	Workspace: workspace,
})
```

## Unclear
Can you please clarify, do I need to run submit-pr-for-drift-detect.yml manually before  atlantis-drift-detection.yml ?
Or atlantis-drift-detection submits it ?
It is unclear from README

Thanks
